# Generated by Django 4.1.1 on 2023-05-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_comment_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='lang',
        ),
    ]
